services:
  - type: web
    name: stremio-sosac
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DEBUG_STREAMUJ_RAW
        value: 0
